### ISSUE TITLE
CMake not working with FetchContent

### ISSUE THREAD

**Issue by pfriesch** [Skycoder42/QHotkey#24]
CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.14)
project(qhotkey_test)

set(CMAKE_CXX_STANDARD 14)

include(FetchContent)
FetchContent_Declare(
        qhotkey
        GIT_REPOSITORY https://github.com/Skycoder42/QHotkey.git
        GIT_TAG        master
)


add_executable(qhotkey_test main.cpp)

FetchContent_MakeAvailable(qhotkey)

```

main.cpp:
```c++
#include <iostream>

#include <QHotkey>


int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```
When making this test project, I get `fatal error: 'QHotkey' file not found`.  Maybe @mujx knows more?

**Comment by Skycoder42** [comment]
I do not know about FetchContent. If it does not work with the repository, that thats a problem of that tool, not the repository.

However, the reason is most likely that sources are in the `QHotkey` subfolder. You propably have to pass some extra arguments to tell FetchContent where to find the sources

**Comment by Skycoder42** [comment]
Checking the [Documentation](https://cmake.org/cmake/help/latest/module/FetchContent.html) of FetchContent, you propably have to do it in multiple steps and specify a custom path.
