### ISSUE TITLE
Issue with "qpm install de.skycoder42.qhotkey"

### ISSUE THREAD

**Issue by GnanaShekhar** [Skycoder42/QHotkey#5]
When I tried installing using the command "qpm install de.skycoder42.qhotkey", I got the following issue:

QPM: 2017/06/09 06:36:44 ERROR: GetFileAttributesEx 
\app2\vendor\Skycoder42-QHotkey-a0678c4\doc\qpm.json: The system cannot find the file specified.

So, I checked for the file and its missing in the repository too.

**Comment by Skycoder42** [comment]
This is an error of qpm. See Cutehacks/qpm#41. I know it's a bother, but this seems to be an windows specific problem.

Until it is fixed, it seems creating the file yourself works as a workaround. If you can verify this, I can put a dummy file inside there.

**Comment by Skycoder42** [comment]
The error has already been fixed in master, but has not been released yet. Until 0.11.0 has been released, you can download the binary from here: 

https://storage.googleapis.com/www.qpm.io/download/latest/windows_amd64/qpm.exe
https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm.exe
