### ISSUE TITLE
building with cmake build for a Debug Config automatically if you don't precise it in the "--build" step

### ISSUE THREAD

**Issue by RedaMazoz** [Skycoder42/QHotkey#75]
Hi, I've tried to build the project in windows, but I noticed that when I do `cmake --install build` cmake couldn't find the .lib file because cmake was building for a Debug  config while it the last command asked for a Release config

Please add to the documentation that people should use
`cmake --build build --config release` instead of just saying `cmake --build build`

Just wanted to help others that would've struggled :)

**Comment by Shatur** [comment]
It's because some generators such as Visual Studio on Windows are multi-config. I.e. you need to select the build type at the build step, not at the configuration step. It's not specific to Windows, [see](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html).
Building C++ projects have a lot of nuances. I'm not sure if it possible to document everything. But feel free to open a PR for it.
